# Generated by Django 5.2 on 2025-04-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_initial', models.FloatField(default=500)),
                ('delai_livraison', models.IntegerField(default=2)),
                ('cout_passation_commande', models.FloatField(default=100)),
                ('prix_unitaire', models.FloatField(default=20)),
                ('taux_possession', models.FloatField(default=0.1)),
                ('stock_securite', models.FloatField(default=300)),
            ],
        ),
        migrations.CreateModel(
            name='DemandePrevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('valeur', models.FloatField()),
            ],
            options={
                'unique_together': {('trimestre', 'annee')},
            },
        ),
    ]
