# Generated by Django 5.2 on 2025-05-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
