# Generated by Django 5.2 on 2025-05-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0004_userprofile_date_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepot',
            name='ville',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entrepot',
            name='adresse',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
