# Generated by Django 5.2 on 2025-05-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0005_entrepot_ville_alter_entrepot_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepot',
            name='surface',
            field=models.IntegerField(null=True),
        ),
    ]
