# Generated by Django 5.2 on 2025-05-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0006_entrepot_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='entrepots',
            field=models.ManyToManyField(to='pfa.entrepot'),
        ),
    ]
