# Generated by Django 5.2 on 2025-05-24 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0007_product_entrepots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('date_sortie', models.DateTimeField(auto_now_add=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('entrepot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfa.entrepot')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorties', to='pfa.product')),
            ],
        ),
    ]
