# Generated by Django 5.2 on 2025-05-25 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0008_sortie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='entrepots',
        ),
        migrations.AddField(
            model_name='product',
            name='entrepots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfa.entrepot'),
        ),
    ]
