# Generated by Django 5.2 on 2025-05-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0009_remove_product_entrepots_product_entrepots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='entrepots',
        ),
        migrations.AddField(
            model_name='product',
            name='entrepots',
            field=models.ManyToManyField(to='pfa.entrepot'),
        ),
    ]
