# Generated by Django 5.2 on 2025-05-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0010_remove_product_entrepots_product_entrepots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortie',
            name='entrepot',
        ),
        migrations.AddField(
            model_name='sortie',
            name='entrepot',
            field=models.ManyToManyField(to='pfa.entrepot'),
        ),
    ]
