# Generated by Django 5.2 on 2025-05-25 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0011_remove_sortie_entrepot_sortie_entrepot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortie',
            name='entrepot',
        ),
    ]
