# Generated by Django 5.2 on 2025-05-25 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0012_remove_sortie_entrepot'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pfa.entrepot'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfa.product'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='quantite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='remarque',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
