# Generated by Django 5.2 on 2025-05-26 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0014_userloginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reapprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField()),
                ('date_reception', models.DateTimeField()),
                ('quantite', models.IntegerField()),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfa.entrepot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfa.product')),
            ],
        ),
    ]
