# Generated by Django 5.2 on 2025-05-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0015_reapprovisionnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepot',
            name='cout_fixe_annuel',
            field=models.FloatField(default=0.0, verbose_name="Coût fixe annuel de l'entrepôt"),
        ),
        migrations.AddField(
            model_name='entrepot',
            name='cout_variable_unitaire',
            field=models.FloatField(default=0.0, verbose_name='Coût variable par unité stockée'),
        ),
    ]
