# Generated by Django 5.2 on 2025-05-26 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0016_entrepot_cout_fixe_annuel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='entrepots',
        ),
        migrations.AddField(
            model_name='product',
            name='entrepots',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pfa.entrepot'),
            preserve_default=False,
        ),
    ]
