# Generated by Django 5.2 on 2025-05-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0017_remove_product_entrepots_product_entrepots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='entrepots',
            new_name='entrepot',
        ),
    ]
