# Generated by Django 5.2 on 2025-05-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0018_rename_entrepots_product_entrepot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='entrepot',
            new_name='entrepots',
        ),
    ]
