# Generated by Django 5.2 on 2025-05-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0019_rename_entrepot_product_entrepots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepot',
            name='cout_fixe_annuel',
            field=models.FloatField(default=500.0, verbose_name="Coût fixe annuel de l'entrepôt"),
        ),
        migrations.AlterField(
            model_name='entrepot',
            name='cout_variable_unitaire',
            field=models.FloatField(default=10.0, verbose_name='Coût variable par unité stockée'),
        ),
    ]
