# Generated by Django 5.2 on 2025-05-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0020_alter_entrepot_cout_fixe_annuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='motif_sortie',
            field=models.CharField(choices=[('VENTE', 'Vente'), ('PERTE', 'Perte'), ('CASSE', 'Casse'), ('TRANSFERT', 'Transfert'), ('RETOUR', 'Retour'), ('AUTRE', 'Autre')], default='VENTE', max_length=50),
        ),
    ]
