# Generated by Django 5.2 on 2025-05-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0021_sortie_motif_sortie'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delai_reappro_moyen',
            field=models.IntegerField(default=7, help_text='Délai de réapprovisionnement moyen en jours'),
        ),
        migrations.AddField(
            model_name='product',
            name='facteur_z',
            field=models.DecimalField(decimal_places=2, default=1.96, help_text='Facteur Z pour le niveau de service (1.96 = 97.5%)', max_digits=4),
        ),
    ]
