# Generated by Django 5.2 on 2025-05-27 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0022_product_delai_reappro_moyen_product_facteur_z'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='derniere_prevision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prevision_activee',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PrevisionWilson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_optimale', models.IntegerField()),
                ('point_commande', models.IntegerField()),
                ('cout_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previsions_mensuelles', models.JSONField()),
                ('date_prevision', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfa.product')),
            ],
            options={
                'ordering': ['-date_prevision'],
            },
        ),
    ]
