# Generated by Django 5.2 on 2025-05-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0023_product_derniere_prevision_product_prevision_activee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='derniere_prevision',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prevision_activee',
        ),
    ]
