# Generated by Django 5.2 on 2025-05-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0024_remove_product_derniere_prevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='derniere_prevision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prevision_activee',
            field=models.BooleanField(default=False),
        ),
    ]
