# Generated by Django 5.2 on 2025-05-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0026_remove_product_derniere_prevision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresEOQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_possession', models.DecimalField(decimal_places=4, default=0.15, help_text='Taux de possession annuel (ex: 0.15 pour 15%)', max_digits=5)),
                ('cout_commande_defaut', models.DecimalField(decimal_places=2, default=50, help_text='Coût fixe par commande par défaut', max_digits=10)),
            ],
            options={
                'verbose_name': 'Paramètres EOQ',
                'verbose_name_plural': 'Paramètres EOQ',
            },
        ),
    ]
