# Generated by Django 5.2 on 2025-05-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0028_validationproduit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='validation_status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('a_discuter', 'À discuter'), ('non_demande', 'Non demandé')], default='non_demande', max_length=20),
        ),
        migrations.DeleteModel(
            name='ValidationProduit',
        ),
    ]
