# Generated by Django 5.2 on 2025-05-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0029_product_validation_status_delete_validationproduit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrevisionWilson',
        ),
    ]
